### ISSUE TITLE
blender

### ISSUE THREAD

**Issue by mm132** [HENDRIX-ZT2/bfb-blender#2]
The traceback error pops up when I try to upload NIF files on Blender.

**Comment by HENDRIX-ZT2** [comment]
This plugin is not for NIFs. You need this instead: https://github.com/HENDRIX-ZT2/blender_nif_plugin
If the error persists, open a more detailed issue there.
Closed.

**Comment by neomonkeus** [comment]
@mm132 Also if you are going to write an issue, please us know what version of the plugin and actual output from the plugin. Thanks. 

@HENDRIX-ZT2 Presume you meant https://github.com/niftools/blender_nif_plugin as your repo doesn't have issues enabled?
