### ISSUE TITLE
Upgrade to 2.8x Required Despite Using Blender 2.82

### ISSUE THREAD

**Issue by Mjmannella** [HENDRIX-ZT2/bfb-blender#3]
![Visual](https://user-images.githubusercontent.com/59515049/75201366-470b6100-5736-11ea-9e8d-7a1ba44d9024.png)
Today I installed Blender 2.82 and the bfb-blender plugin, only to to get a error where I need to upgrade to a version it should already be compatible with.

**Comment by HENDRIX-ZT2** [comment]
Was that the 2.8 branch of the tools?

**Comment by Mjmannella** [comment]
I'm not sure. I downloaded the plugin from [here.](https://github.com/HENDRIX-ZT2/bfb-blender) and tried to install it in the preferences menu.
I was able to get the plugin to work using Blender 2.79, if that helps any.

**Comment by HENDRIX-ZT2** [comment]
Yeah that's not the 2.8 branch:
https://github.com/HENDRIX-ZT2/bfb-blender/tree/blender2.80

**Comment by Mjmannella** [comment]
Thanks for letting me know about that!

**Comment by HENDRIX-ZT2** [comment]
Sure. I'm not sure how functional the 2.8 port was. Import should be fine but export is probably lacking.

**Comment by Mjmannella** [comment]
I will keep this in mind. Thank you for addressing my issue!

**Comment by dinoking27** [comment]
i was about to install the Import and export version of 2.8 but it was showing this something about  
![image](https://user-images.githubusercontent.com/74396932/102968542-0a2d0980-44c2-11eb-8c4f-5f659f45a482.png)
 but its being a pain to me how can I fix it plz and thank you
