### ISSUE TITLE
bone_tools.reorient_bone doesn't work?

### ISSUE THREAD

**Issue by TiberiumFusion** [HENDRIX-ZT2/bfb-blender#4]
Hello,

I found this repo from your StackOverflow answer at: [https://blender.stackexchange.com/questions/29000/rotate-a-particular-bone-in-edit-mode-without-offsetting-animation](https://blender.stackexchange.com/questions/29000/rotate-a-particular-bone-in-edit-mode-without-offsetting-animation). I'm looking for a way to edit bone roll without breaking posed animations, so I was really happy to find the code you posted to answer that question.

However... it doesn't work for me. I might be using it wrong, but `reorient_bone` doesn't produce the correct rotation or fcurve modifications. I'm hoping you can tell what's gone wrong.

#### Here's what I've tried:
1. Blend file I'm using for this demo: [https://drive.google.com/open?id=1MP4tGWqbtsuZ5agtZFDDUVPe2ayJ8jRi](https://drive.google.com/open?id=1MP4tGWqbtsuZ5agtZFDDUVPe2ayJ8jRi)). I'm using latest version of `reorient_bone` from this repo (June 28 2018) in Blender 2.79.
2. Here's the rest pose of the armature I'm working with:
![slide 1](https://user-images.githubusercontent.com/6332277/76674975-4d4d6a00-658b-11ea-84c5-3eea487df779.png)
3. Here's the simple, one-frame animated pose it has:
![slide 2](https://user-images.githubusercontent.com/6332277/76675006-a5846c00-658b-11ea-9431-e1b0131e30ff.png)
3. The selected bone currently has a roll of 137 degrees. I'd like to use your `reorient_bone` method to change it to 50 degrees while preserving the posed animation.
4. I run `reorient_bone` with `Location` set to `0, 0, 0`, `Rotation` set to `0, -87, 0`, and `Anim Mode` set to `Bonespace`.
5. The bone now has a bone roll of 50 degrees, which is what I was expecting.
![slide 3](https://user-images.githubusercontent.com/6332277/76675270-e3828f80-658d-11ea-9c65-99cd76179e43.png)
6. However, the animation was *not* preserved. Here is what it looks like now. As you can see, the arm isn't rotated or positioned correctly. Both the bone's location and rotation do not match Step 3.
![slide 4](https://user-images.githubusercontent.com/6332277/76675278-f39a6f00-658d-11ea-9bef-df8f5e017f88.png)
7. By looking at the fcurve, you can see that `reorient_bone` did actually change the fcurve, but whatever changes it made had no real effect. So, `reorient_bone` was just an identity transform.
8. If I simply change the bone roll from 137 to 50 in edit mode using the Properties panel, this is what the pose looks like:
![slide 5](https://user-images.githubusercontent.com/6332277/76675288-0745d580-658e-11ea-8e25-cb7f500c4aa4.png)
9. So, the result from using `reorient_bone` and the result from simply changing the bone roll are visually identical.

#### I've also tried using the older version of `reorient_bone` that you shared in that StackOverflow answer from Feb 4 2018.
1. I followed the exact same steps as above.
2. The bone roll is changed to 50, as I expected:
![slide 6](https://user-images.githubusercontent.com/6332277/76675366-e3cf5a80-658e-11ea-9af7-862e0678a869.png)
3. However, just like in the newer version of `reorient_bone`, the animation is not preserved, and still breaks:
![slide 7](https://user-images.githubusercontent.com/6332277/76675378-f34ea380-658e-11ea-9f36-8092b20653b1.png)
4. As you can see, however, the results between this older `reorient_bone` method and the newer `reorient_bone` method are different. In both versions, the fcurve modifications do not preserve the posed animation, although they fail in different ways.

#### Conclusion
I'm not sure what's going wrong here. Am I using `reorient_bone` incorrectly?  Is there a bug in `reorient_bone`? Am I just wrong about thinking that `reorient_bone` preserves posed animations?

Thank you much in advance.

**Comment by HENDRIX-ZT2** [comment]
It used to work for the very specific cases I needed it for. It probably just worked out of dumb luck.
