### ISSUE TITLE
Update to 2.8x Issue

### ISSUE THREAD

**Issue by dinoking27** [HENDRIX-ZT2/bfb-blender#5]
i did install the addon until it showing this on blender how can I update it to 2.8x mine is at 2.91

how can I fix this problem
![issue](https://user-images.githubusercontent.com/74396932/102675167-601e4c00-4166-11eb-9825-834a4f2b063c.PNG)

**Comment by Mjmannella** [comment]
I can confirm that I have similar issues. I've tried this with 2.81, 2.82, 2.83, and 2.91. All versions had the same issue. However, the add-on works fine with 2.79b.

Unfortunately, I have a diametrically opposite problem with the .nif add-on. It works in 2.81 onward, but not in 2.79. This makes it borderline impossible to have a model be converted from a .bfb to a .nif an vice-versa.

**Comment by HENDRIX-ZT2** [comment]
Are you using this branch?
https://github.com/HENDRIX-ZT2/bfb-blender/tree/blender2.80

**Comment by dinoking27** [comment]
yes

**Comment by HENDRIX-ZT2** [comment]
From the screenshot it does not appear that you are doing so.

**Comment by dinoking27** [comment]
sorry about that i must have used the master version of it

**Comment by HENDRIX-ZT2** [comment]
Use this branch to avoid naming issues:
https://github.com/HENDRIX-ZT2/bfb-blender/tree/blender29

**Comment by dinoking27** [comment]
Thanks for the tip! it finally works

**Comment by dinoking27** [comment]
i did hit the little box with the checkmark on it it may have worked but it doesn't show the models when I hit import on it because I did download the models looking for the Z2F on but it doesn't show BFB on it sorry to be a pain to you

**Comment by jerkingaboutmyself** [comment]
but no Z2F? oh come on man!
